class Completion:
    def __init__(self, gpt3_instance):
        self.gpt3_instance = gpt3_instance
    
    def complete_text(self, prompt, max_tokens=50, temperature=0.7):
        """
        Complete a given prompt using OpenAI's GPT-3 model.
        
        Args:
            prompt (str): The input text prompt to complete.
            max_tokens (int): The maximum number of tokens to generate (default: 50).
            temperature (float): Controls the randomness of the generated text. Higher values lead to more randomness (default: 0.7).
        
        Returns:
            str: The completed text generated by the GPT-3 model.
        """
        try:
            # Call OpenAI's completion API
            response = self.gpt3_instance.complete(prompt, max_tokens=max_tokens, temperature=temperature)
            completed_text = response['choices'][0]['text'].strip()
            return completed_text
        except Exception as e:
            print("Error completing text:", e)
            return None
